### ISSUE TITLE
Rotation can not be turned off via switch

### ISSUE THREAD

**Issue by Nastras** [SeydX/homebridge-star-projector#1]
Hello @SeydX,

i have tested the plugin and it works really well. Great work! I noticed that the rotation can not be stopped via the switch. If I reduce the slider from 100 to 0 it works.

Would be nice if you could check?

Thanks!

**Comment by seydx** [comment]
Which switch is it exactly? The switch of "Rotation" ? Or the main switch that turns off the projector?

**Comment by Nastras** [comment]
Rotation

**Comment by seydx** [comment]
Yes, that is correct. The "Active" switch of Rotation is without function because "Rotation" cannot be switched off completely (the Tuya API does not allow it). Rotation always has a min value of 1. I have also changed the allowed minValue in the backend to "1" (hap). Therefore it is best to switch on/off directly via the slider.

**Comment by seydx** [comment]
Fixed in v1.0.4

**Comment by Nastras** [comment]
Works great! Thanks!

I sent you a PN to the fritz-platform in the forum.
